name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx ablog alabaster myst_parser sphinxext-opengraph[social-cards]
      - name: Sphinx linkcheck
        run: |
          sphinx-build -b linkcheck -W -n -a -E doc _build/linkcheck
          # sphinx-build -b linkcheck -W -n -a -E doc doc/linkcheck
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linkcheck
          path: _build/linkcheck
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
